"""20221212_1450

Revision ID: d27f7b629af1
Revises: 
Create Date: 2022-12-12 14:50:23.755809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27f7b629af1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('ccn_role', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=True),
    sa.Column('full_role', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('ccn_role')
    )
    op.create_table('tbl_type_id',
    sa.Column('ccn_type_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.String(length=2), nullable=False),
    sa.Column('description_type_id', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ccn_type_id')
    )
    op.create_table('tbl_employee',
    sa.Column('ccn_employee', sa.Integer(), nullable=False),
    sa.Column('ccn_type_id', sa.Integer(), nullable=True),
    sa.Column('number_id_employee', sa.Integer(), nullable=False),
    sa.Column('first_name_employee', sa.String(length=30), nullable=False),
    sa.Column('middle_name_employee', sa.String(length=30), nullable=True),
    sa.Column('first_last_name_employee', sa.String(length=30), nullable=False),
    sa.Column('second_last_name_employee', sa.String(length=30), nullable=True),
    sa.Column('full_name_employee', sa.String(length=200), nullable=False),
    sa.Column('date_birth_employee', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('employee_personal_email', sa.String(length=100), nullable=False),
    sa.Column('employee_personal_cellphone', sa.String(length=40), nullable=False),
    sa.Column('informed_consent_law_1581', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('employee_password', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['ccn_type_id'], ['tbl_type_id.ccn_type_id'], ),
    sa.PrimaryKeyConstraint('ccn_employee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_employee')
    op.drop_table('tbl_type_id')
    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
